name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
        compiler:
          - llvm
        d:
          - "ldc-latest"
          - "dmd-latest"
    steps:
      - uses: actions/checkout@v4

      # Cache
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.dub
            ~/AppData/Local/dub
          key: "cache--OS:${{ matrix.os }}"

      # Setup compilers and tools

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true

      # Build and Test

      - name: Build
        run: make build

      - name: Test
        run: make unit

      - name: Benchmarks
        run: make benchmark

      # Bindings tests
      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.d }}

      - name: Build and Test D Binings
        continue-on-error: ${{ contains(matrix.os, 'macos') }}
        run: |
          dub build
          dub test
